apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"name":"my-app-dev","namespace":"argocd"},"spec":{"destination":{"namespace":"backend","server":"https://kubernetes.default.svc"},"project":"default","source":{"helm":{"releaseName":"my-app","values":"image:\n  tag: 8\n"},"path":"./","repoURL":"https://github.com/Ahmad-Faqehi/helm-chart.git","targetRevision":"main"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"syncOptions":["CreateNamespace=true"]}}}
  creationTimestamp: "2026-01-03T10:12:48Z"
  generation: 610
  name: my-app-dev
  namespace: argocd
  resourceVersion: "357300"
  uid: 00ec073e-5014-4abd-af48-4cb64850720d
spec:
  destination:
    namespace: backend
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: my-app
      values: |
        image:
          tag: 8
    path: ./
    repoURL: https://github.com/Ahmad-Faqehi/helm-chart.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2026-01-03T10:32:13Z"
    status: Degraded
  history:
  - deployStartedAt: "2026-01-03T10:12:51Z"
    deployedAt: "2026-01-03T10:12:52Z"
    id: 0
    initiatedBy:
      automated: true
    revision: 87671b246b336f10c45467f31981533c47a71eec
    source:
      helm:
        releaseName: my-app
        valueFiles:
        - values.yaml
      path: ./
      repoURL: https://github.com/Ahmad-Faqehi/helm-chart.git
      targetRevision: main
  - deployStartedAt: "2026-01-03T10:21:44Z"
    deployedAt: "2026-01-03T10:21:45Z"
    id: 1
    initiatedBy:
      automated: true
    revision: 87671b246b336f10c45467f31981533c47a71eec
    source:
      helm:
        releaseName: my-app
        values: |
          image:
            tag: 20
      path: ./
      repoURL: https://github.com/Ahmad-Faqehi/helm-chart.git
      targetRevision: main
  - deployStartedAt: "2026-01-03T10:22:10Z"
    deployedAt: "2026-01-03T10:22:12Z"
    id: 2
    initiatedBy:
      automated: true
    revision: 87671b246b336f10c45467f31981533c47a71eec
    source:
      helm:
        releaseName: my-app
        values: |
          image:
            tag: 8
      path: ./
      repoURL: https://github.com/Ahmad-Faqehi/helm-chart.git
      targetRevision: main
  operationState:
    finishedAt: "2026-01-03T10:22:12Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revision: 87671b246b336f10c45467f31981533c47a71eec
        source:
          helm:
            releaseName: my-app
            values: |
              image:
                tag: 8
          path: ./
          repoURL: https://github.com/Ahmad-Faqehi/helm-chart.git
          targetRevision: main
        syncOptions:
        - CreateNamespace=true
    phase: Succeeded
    startedAt: "2026-01-03T10:22:10Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: ServiceAccount
        message: serviceaccount/my-app-backend-blog-api unchanged
        name: my-app-backend-blog-api
        namespace: backend
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/my-app-backend-blog-api unchanged
        name: my-app-backend-blog-api
        namespace: backend
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        images:
        - ahmad75/blog-api:8
        kind: Deployment
        message: deployment.apps/my-app-backend-blog-api configured
        name: my-app-backend-blog-api
        namespace: backend
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 87671b246b336f10c45467f31981533c47a71eec
      source:
        helm:
          releaseName: my-app
          values: |
            image:
              tag: 8
        path: ./
        repoURL: https://github.com/Ahmad-Faqehi/helm-chart.git
        targetRevision: main
  reconciledAt: "2026-01-04T13:04:51Z"
  resourceHealthSource: appTree
  resources:
  - kind: Service
    name: my-app-backend-blog-api
    namespace: backend
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: my-app-backend-blog-api
    namespace: backend
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: my-app-backend-blog-api
    namespace: backend
    status: Synced
    version: v1
  sourceHydrator: {}
  sourceType: Helm
  summary:
    images:
    - ahmad75/blog-api:20
    - ahmad75/blog-api:8
  sync:
    comparedTo:
      destination:
        namespace: backend
        server: https://kubernetes.default.svc
      source:
        helm:
          releaseName: my-app
          values: |
            image:
              tag: 8
        path: ./
        repoURL: https://github.com/Ahmad-Faqehi/helm-chart.git
        targetRevision: main
    revision: 87671b246b336f10c45467f31981533c47a71eec
    status: Synced
